banquet_list = ['my','csy','hft','lgl','hyd']
print(banquet_list)
print(f"Long time no see,{banquet_list}.Excuse me,are you free for a part?")
print('My have no time to the party')
banquet_list.remove('my')
banquet_list.insert(0,'bwq')
print(f"Long time no see,{banquet_list}.Excuse me,are you free for a part?")
banquet_list.insert(1,'xy')
banquet_list.insert(3,'gzj')
banquet_list.append('lxc')
print(banquet_list)
print("I'm sorry, but for some reason I can only entertain two people")
a = banquet_list.pop()
b = banquet_list.pop()
c = banquet_list.pop()
d = banquet_list.pop()
e = banquet_list.pop()
f = banquet_list.pop()
print(banquet_list)
print(f"I'm sorry fpr {a}, but for some reason I can only entertain two people")
print(f"I'm sorry fpr {b}, but for some reason I can only entertain two people")
print(f"I'm sorry fpr {c}, but for some reason I can only entertain two people")
print(f"I'm sorry fpr {d}, but for some reason I can only entertain two people")
print(f"I'm sorry fpr {e}, but for some reason I can only entertain two people")
print(f"I'm sorry fpr {f}, but for some reason I can only entertain two people")
del banquet_list[0]
del banquet_list[0]
print(banquet_list)